name: implicitly_animated_reorderable_list
description: A Flutter ListView that implicitly animates between the changes of two lists the support to reorder its items.
version: 0.1.0
homepage: https://github.com/BendixMa/implicitly_animated_reorderable_list/tree/master/example/lib/ui

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: